### ISSUE TITLE
Dependency uses GPL 2.0 license - Replace Colorize

### ISSUE THREAD

**Issue by gabrielqueiroz** [clio/ten_years_rails#19]
We are currently adding `ten_years_rails` in our app, and one of our security tools got a vulnerability on using this gem. Basically `ten_years_rails` is using `colorized` which is under GPL-2.0 license. The license enforces that _"the source code of the work must be made available under the same license"_. As far as I could understand we shouldn't be using it on a private project, even if the `ten_years_rails` is under MIT license.

There is [an issue on colorized regarding this](https://github.com/fazibear/colorize/issues/47), and there is also another gem that could replace colorize for this case. Gitlab CE had a similar issue and created this PR: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/4425.

Let me know if I can help with anything or if you have another interpretation for this.

**Comment by gavingmiller** [comment]
Thank you for bringing this issue to our attention @gabrielqueiroz. I've flagged this issue internally for us to review.
