### ISSUE TITLE
bin/next command source code?

### ISSUE THREAD

**Issue by jmgarnier** [clio/ten_years_rails#5]
My friend @pcreux pinged me about your talk and I really liked it 👏 

Would you be so kind to share `bin/next command source code`, or it only 1 bash script ?

![image](https://user-images.githubusercontent.com/8051/48091811-0e770980-e20b-11e8-9d80-2389cbd9645a.png)

It would be nice to have a way to Run Rails next on `production` or even better `staging` and see what CI did not catch :)

**Comment by jnraine** [comment]
@jmgarnier I'm sorry for the _very_ delayed reply!

The source code for `bin/next` is hiding in this repo. It is a simple bash script but evolved a bit to improve error handling. When running Rails next in production, we set environment variables as shown in the screenshot when starting up the application and it works well.

Check it out: https://github.com/clio/ten_years_rails/blob/master/exe/next.sh

**Comment by jmgarnier** [comment]
🤦‍♂️ I could have found it :)

Thank you!
